name 'localization'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures localization'
long_description 'Installs/Configures localization'
version '0.1.0'
